from enum import Enum

class ReasonCode(str, Enum):
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    CORRUPT_AUDIO = "CORRUPT_AUDIO"
    DURATION_TOO_SHORT = "DURATION_TOO_SHORT"
    DURATION_TOO_LONG = "DURATION_TOO_LONG"
    SILENCE_ONLY = "SILENCE_ONLY"
    INSUFFICIENT_SPEECH = "INSUFFICIENT_SPEECH"
    NOISY_AUDIO = "NOISY_AUDIO"
    LOW_VOLUME = "LOW_VOLUME"
    AUDIO_CLIPPING_DETECTED = "AUDIO_CLIPPING_DETECTED"
    BACKGROUND_MUSIC_DETECTED = "BACKGROUND_MUSIC_DETECTED"
    OVERLAPPING_VOICES_DETECTED = "OVERLAPPING_VOICES_DETECTED"
    MULTIPLE_SPEAKERS_DETECTED = "MULTIPLE_SPEAKERS_DETECTED"
    SPEECH_UNCLEAR = "SPEECH_UNCLEAR"
    SPEECH_TOO_SLOW = "SPEECH_TOO_SLOW"
    SPEECH_TOO_FAST = "SPEECH_TOO_FAST"
    TONE_INCONSISTENT = "TONE_INCONSISTENT"
    SPEAKER_MISMATCH_ACROSS_FILES = "SPEAKER_MISMATCH_ACROSS_FILES"

# I/O Thresholds
MAX_FILE_SIZE_BYTES = 25 * 1024 * 1024  # 25 MB
MIN_DURATION_SECONDS = 3.0
MAX_DURATION_SECONDS = 30.0
TARGET_SAMPLE_RATE = 16000

# VAD / Silence Thresholds
MIN_SPEECH_PROPORTION = 0.20  # 20%

# Noise Thresholds
MIN_SNR_DB = 15.0  # Decibels

# Loudness Thresholds
MIN_LUFS = -35.0

# Background Music Thresholds
MUSIC_CLASS_THRESHOLD = 0.40 # Minimum confidence to consider music present

# Overlap Thresholds
MAX_OVERLAP_TOLERANCE_SECONDS = 2.5

# Speaker Diarization
CLUSTER_SHARE_MINIMUM = 0.10 # e.g. 10%
DIARIZATION_DISTANCE_THRESHOLD = 0.7  # Cosine distance for ECAPA-TDNN

# Speech Clarity (Whisper)
MIN_AVG_LOGPROB = -0.8
WHISPER_MODEL_SIZE = "tiny"

# Pace
MIN_WORDS_PER_MINUTE = 100
MAX_WORDS_PER_MINUTE = 200 # Advisory
